baseURL = 'https://changerlemond.netlify.app/'
languageCode = 'ko-kr'
title = 'í‰ë²”í•œ ê°œë°œìì˜ ì†Œì†Œí•œ ì´ì•¼ê¸°'
theme = "github-style"

[params]
author = "Claire Jung"
description = "If you run code, world changes."
github = "changerlemond"
#facebook = ""
#twitter = ""
linkedin = "changerlemond"
#instagram = ""
#tumblr = ""
email = "dev.jungclaire@gmail.com"
url = "https://linktr.ee/changerlemond"
keywords = "blog"
rss = false
userStatusEmoji = "ğŸ’Œ"
favicon = "/images/github.png"
location = "Seoul, Republic of Korea"
enableGitalk = true

[params.gitalk]
clientID = "d8c75cc0140236fff6fe"
clientSecret = "f2bc81809043695a10172c2cedb32674b315b5bb"
repo = "changerlemond-blog"
owner = "changerlemond"
admin = "changerlemond"
id = "location.pathname"
labels = "gitalk"
perPage = 30
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true