baseURL = 'https://jungclaire.netlify.app/'
languageCode = 'ko-kr'
title = 'í‰ë²”í•œ ê°œë°œìì˜ ì†Œì†Œí•œ ì´ì•¼ê¸°'
theme = "github-style"

[params]
author = "jungclaire"
description = "Software Engineer"
github = "jungclaire"
#facebook = "MeiK2333"
#twitter = "MeiK2333"
linkedin = "seunghee-jung-claire"
instagram = "jungclaire__"
#tumblr = "MeiK2333"
email = "dev.jungclaire@gmail.com"
#url = "https://github.com/jungclaire"
keywords = "blog"
rss = false
lastmod = true
userStatusEmoji = "ğŸ’œ"
favicon = "/images/github.png"
location = "Seoul, Republic of Korea"
enableGitalk = true

[params.gitalk]
clientID = "b5cbdc5c9072d95c0f39"
clientSecret = "b2b73c48f61a492cd160f6ca6fd547dd64cf5417"
repo = "claire-blog"
owner = "jungclaire"
admin = "jungclaire"
id = "location.pathname"
labels = "gitalk"
perPage = 30
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false