baseURL = 'https://jungclaire.netlify.app/'
languageCode = 'ko-kr'
title = 'í‰ë²”í•œ ê°œë°œìì˜ ì†Œì†Œí•œ ì´ì•¼ê¸°'
theme = "github-style"

[params]
author = "jungclaire"
description = "Software Engineer"
github = "jungclaire"
#facebook = "MeiK2333"
#twitter = "MeiK2333"
linkedin = "seunghee-jung-claire"
instagram = "jungclaire__"
#tumblr = "MeiK2333"
email = "dev.jungclaire@gmail.com"
#url = "https://github.com/jungclaire"
keywords = "blog"
rss = false
lastmod = true
userStatusEmoji = "ğŸ’œ"
favicon = "/images/github.png"
location = "Seoul, Republic of Korea"
#enableGitalk = true

[params.gitalk]
clientID = "jungclaire"
clientSecret = "Your client secret"
repo = "https://github.com/jungclaire/claire-blog"
owner = "jungclaire"
admin = "jungclaire"
id = "location.pathname"
labels = "blog"
perPage = 30
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false